//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.30 at 02:52:25 PM MSK 
//


package code;

import javax.xml.bind.annotation.XmlRegistry;
import java.util.List;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the generated package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     */
    ObjectFactory() {
    }

    /**
     * Create an instance of {@link SimpleCalculator }
     */
    public SimpleCalculator createSimpleCalculator() {
        return new SimpleCalculator();
    }

    /**
     * Create an instance of {@link SimpleCalculator.ExpressionResults }
     */
    SimpleCalculator.ExpressionResults createSimpleCalculatorExpressionResults(List<SimpleCalculator.ExpressionResults.ExpressionResult> results) {
        SimpleCalculator.ExpressionResults res = new SimpleCalculator.ExpressionResults();
        res.expressionResult = results;
        return res;
    }

    /**
     * Create an instance of {@link SimpleCalculator.Expressions }
     */
    public SimpleCalculator.Expressions createSimpleCalculatorExpressions() {
        return new SimpleCalculator.Expressions();
    }

    /**
     * Create an instance of {@link Term }
     */
    public Term createTerm() {
        return new Term();
    }

    /**
     * Create an instance of {@link SimpleCalculator.ExpressionResults.ExpressionResult }
     */
    SimpleCalculator.ExpressionResults.ExpressionResult createSimpleCalculatorExpressionResultsExpressionResult(double result) {
        SimpleCalculator.ExpressionResults.ExpressionResult res = new SimpleCalculator.ExpressionResults.ExpressionResult();
        res.setResult(result);
        return res;
    }

    /**
     * Create an instance of {@link SimpleCalculator.Expressions.Expression }
     */
    public SimpleCalculator.Expressions.Expression createSimpleCalculatorExpressionsExpression() {
        return new SimpleCalculator.Expressions.Expression();
    }

}
